export const BOOKS = [
  ['stax-amfg', 'Additive Manufacturing'],
  ['stax-usgovt', 'American Government'],
  ['stax-anp', 'Anatomy and Physiology'],
  ['stax-anth', 'Anthropology'],
  ['stax-bio', 'Biology'],
  ['stax-apbio', 'Biology for AP® Courses'],
  ['stax-bca', 'Business Computer Applications'],
  ['stax-phys', 'College Physics'],
  ['stax-apphys', 'College Physics for AP® Courses'],
  ['stax-pyth', 'Computer Programming with Python'],
  ['stax-cs', 'Computer Science'],
  ['stax-cbio', 'Concepts of Biology'],
  ['stax-cmath', 'Contemporary Math'],
  ['stax-devpsy', 'Developmental Psychology'],
  ['stax-econ', 'Economics'],
  ['stax-engcomp', 'English Composition'],
  ['stax-eship', 'Entrepreneurship'],
  ['stax-fin', 'Finance'],
  ['stax-k12phys', 'HS Physics'],
  ['stax-infosys', 'Information Systems'],
  ['stax-macro', 'Macro Economics'],
  ['stax-micro', 'Micro Economics'],
  ['stax-orgchem', 'Organic Chemistry'],
  ['stax-phi', 'Philosophy'],
  ['stax-polisci', 'Political Science'],
  ['stax-mktg', 'Principles of Marketing'],
  ['stax-psy', 'Psychology'],
  ['stax-soc', 'Sociology'],
  ['stax-ushist', 'U.S. History'],
  ['stax-apush', 'U.S. History for AP® Courses'],
  ['stax-worldhist', 'World History'],
  ['stax-matnewborn', 'Maternal Newborn Nursing'],
  ['stax-nursingskills', 'Clinical Nursing Skills'],
  ['stax-psychnursing', 'Psychiatric-Mental Health Nursing'],
  ['stax-medsurg', 'Medical-Surgical Nursing'],
  ['stax-nursingfundamentals', 'Fundamentals of Nursing'],
  ['stax-pharmacology', 'Pharmacology for Nurses'],
  ['stax-nutrition', 'Nutrition'],
  ['stax-pophealth', 'Community-Population Health'],
  ['stax-neuroscience', 'Introduction to Behavioral Neuroscience'],
  ['stax-datascience', 'Data Science'],
  ['stax-accounting', 'Principles of Accounting, Volumes 1-2'],
  ['stax-busethics', 'Business Ethics'],
  ['stax-buslaw', 'Business Law I Essentials'],
  ['stax-ip', 'Intellectual Property'],
  ['stax-stats', 'Introductory Statistics'],
  ['stax-busstats', 'Introductory Business Statistics'],
  ['stax-introbus', 'Introduction to Business'],
  ['stax-orgbehavior', 'Organizational Behavior'],
  ['stax-pom', 'Principles of Management'],
  ['stax-csuccess', 'College Success'],
  ['stax-prepcsuccess', 'Preparing for College Success'],
  ['stax-algtrig', 'Algebra and Trigonometry'],
  ['stax-precal', 'Precalculus'],
  ['stax-calgebra', 'College Algebra'],
  ['stax-coreqalgebra', 'College Algebra with Corequisite Skills'],
  ['stax-calc', 'Calculus vol 1-3'],
  ['stax-elemalgebra', 'Elementary Algebra'],
  ['stax-prealgebra', 'Prealgebra'],
  ['stax-interalgebra', 'Intermediate Algebra'],
  ['stax-hsstats', 'Statistics (high school)'],
  ['stax-astro', 'Astronomy'],
  ['stax-microbio', 'Microbiology'],
  ['stax-chem', 'Chemistry, Chemistry Atoms First'],
  ['stax-uphysics', 'University Physics'],
  ['stax-calculo', 'Cálculo Volumen 1-3'],
  ['stax-ufisica', 'Física Universitaria'],
  ['stax-estadistica', 'Introducción a la estadística'],
  ['stax-estadisticaempresarial', 'Introducción a la estadística empresarial'],
  ['stax-precalculo', 'Precálculo'],
  ['stax-quimica', 'Química'],
].sort((a, b) => a[1].localeCompare(b[1]));
export const AP_BOOKS = BOOKS.map(([value]) => value).filter((value) =>
  value.startsWith('stax-ap'),
);
export const AP_SCIENCE_BOOKS = ['stax-apphys', 'stax-apbio'];
export const AP_HISTORY_BOOKS = ['stax-apush'];
export const NURSING_BOOKS = [
  'stax-matnewborn',
  'stax-nursingskills',
  'stax-psychnursing',
  'stax-medsurg',
  'stax-nursingfundamentals',
  'stax-pharmacology',
  'stax-nutrition',
  'stax-pophealth',
];
